server:
    # EDNS Client Subnet (ECS) Module Configuration
    module-config: "subnetcache validator iterator"
    
    # Send ECS to upstream servers
    send-client-subnet: 127.0.0.1/32
    send-client-subnet: 103.68.212.0/22
    
    # Define which networks are allowed to send ECS info
    client-subnet-always-forward: yes
    
    # ECS Cache sizing
    max-client-subnet-ipv6: 48
    max-client-subnet-ipv4: 24
