server:
    local-zone: "mdnet.co.id." transparent
    local-data: "dns.mdnet.co.id. IN A 103.68.213.74"
    local-data-ptr: "103.68.213.74 dns.mdnet.co.id"
    local-data: "radius.mdnet.co.id. IN A 103.68.213.211"

