server:
    num-threads: 16
    msg-cache-slabs: 16
    rrset-cache-slabs: 16
    infra-cache-slabs: 16
    key-cache-slabs: 16
    msg-cache-size: 256m
    rrset-cache-size: 512m
    outgoing-range: 8192
    num-queries-per-thread: 4096
    so-rcvbuf: 8m
    so-sndbuf: 8m
    so-reuseport: yes
    prefetch: yes
    prefetch-key: yes
    cache-min-ttl: 300
    cache-max-ttl: 86400
    serve-expired: yes
