# DNS MDNET Main Config (ISP SCALE)
port=53
listen-address=127.0.0.1,103.68.213.74
bind-interfaces
server=127.0.0.1#5353
cache-size=10000
dns-forward-max=500000
log-queries
log-facility=/var/log/dnsmasq.log
# EDNS0 Client Subnet (ECS)
# Pass client subnet to Unbound
add-mac
add-cpe-id=64
# conf-file=/etc/dnsmasq.d/internet_positif.conf
filter-rr=ANY
