#!/bin/bash
# Sync DNS Configuration to Secondary Server
# Usage: ./sync_to_secondary.sh [SECONDARY_IP]

# Fetch Secondary IP from WebGUI Database (cluster_status table)
DB_PATH="/home/dns/traffic_history.db"
# Use 'sqlite3' to fetch value. Ensure sqlite3 is installed.
DB_IP=$(sqlite3 "$DB_PATH" "SELECT value FROM cluster_status WHERE key='secondary_ip';" 2>/dev/null)

# Use Argument if provided, otherwise use Database IP
if [ -n "$1" ]; then
    SECONDARY_IP="$1"
elif [ -n "$DB_IP" ]; then
    SECONDARY_IP="$DB_IP"
else
    echo "Error: No Secondary IP found in database (cluster_status) or arguments."
    exit 1
fi

SSH_USER="dns"
SSH_PORT="22"

# Paths to sync
CONFIG_DIRS=(
    "/etc/dnsmasq.d/"
    "/etc/unbound/unbound.conf.d/"
    "/home/dns/blocklists/"
    "/home/dns/whitelist.conf"
    "/home/dns/dnsMars/scripts/"
    "/home/dns/scripts/"
    "/home/dns/web_gui/"
    "/home/dns/guardian.py"
    "/home/dns/guardian_config.json"
    "/home/dns/cdn_config.json"
    "/home/dns/setup_firewall.sh"
    "/home/dns/update_blocklist.sh"
    "/home/dns/sanitize_blocklists.py"
    "/home/dns/smart_verifier.py"
)

echo "[$(date)] Starting Sync to Secondary ($SECONDARY_IP)..."

# 1. Export Trust Schedule
echo "Exporting Trust Schedule..."
sqlite3 "$DB_PATH" ".dump trust_schedule" > /tmp/trust_schedule.sql

# 2. Pre-create directories on Secondary
echo "Ensuring remote directories exist..."
ssh -p $SSH_PORT "$SSH_USER@$SECONDARY_IP" "mkdir -p /home/dns/dnsMars/scripts /home/dns/scripts /home/dns/web_gui /home/dns/blocklists /etc/dnsmasq.d /etc/unbound/unbound.conf.d"

# Detect Remote Interface
echo "Detecting Remote Interface..."
REMOTE_IFACE=$(ssh -p $SSH_PORT "$SSH_USER@$SECONDARY_IP" "ip route get 8.8.8.8 | grep -oP 'dev \K\S+' | head -n 1")
echo "Remote Interface: $REMOTE_IFACE"

# 3. Sync Files
for DIR in "${CONFIG_DIRS[@]}"; do
    if [ -d "$DIR" ] || [ -f "$DIR" ]; then
        echo "Syncing $DIR..."
        # Exclude __pycache__ and local state files
        # We exclude .flask_secret and .password.hash to preserve secondary's own auth if different,
        # but typically in HA they should be same. We'll exclude to be safe unless user wants full clone.
        # We exclude traffic_history.db because we sync trust_schedule separately.
        rsync -avz --delete --exclude '__pycache__' --exclude '*.db' --exclude '.flask_secret' --exclude '.password.hash' -e "ssh -p $SSH_PORT" "$DIR" "$SSH_USER@$SECONDARY_IP:$DIR"
    else
        echo "Warning: $DIR not found, skipping."
    fi
done

# 3. Sync SQL Dump
echo "Syncing Trust Schedule DB Dump..."
scp -P $SSH_PORT /tmp/trust_schedule.sql "$SSH_USER@$SECONDARY_IP:/tmp/trust_schedule.sql"

# 4. Remote Execution
echo "Executing remote update on Secondary..."
ssh -p $SSH_PORT "$SSH_USER@$SECONDARY_IP" "
    # Import Trust Schedule
    if [ -f /tmp/trust_schedule.sql ]; then
        echo 'Importing Trust Schedule...'
        # Drop table first to ensure clean import
        sqlite3 /home/dns/traffic_history.db 'DROP TABLE IF EXISTS trust_schedule;'
        # Import data
        sqlite3 /home/dns/traffic_history.db < /tmp/trust_schedule.sql
        rm -f /tmp/trust_schedule.sql
    fi

    # Ensure permissions (No sudo needed if owned by dns)
    # sudo chown -R dns:dns /home/dns/web_gui /home/dns/scripts
    chmod +x /home/dns/scripts/*.py /home/dns/scripts/*.sh 2>/dev/null
    chmod +x /home/dns/*.sh /home/dns/*.py 2>/dev/null

    # FIX INTERFACE NAME (CRITICAL FOR SECONDARY)
    if [ -n \"$REMOTE_IFACE\" ]; then
        echo \"Fixing interface name to $REMOTE_IFACE on Secondary...\"
        # 1. Update interfaces.conf
        echo -e \"# Auto-generated by sync\ninterface=$REMOTE_IFACE\ninterface=lo\nbind-dynamic\" | sudo -n tee /etc/dnsmasq.d/interfaces.conf > /dev/null || echo \"Warning: Could not update interfaces.conf (sudo required)\"
        
        # 2. IMPORTANT: Remove interface references in other synced files
        sudo -n grep -lR \"interface=\" /etc/dnsmasq.d/ --exclude=\"interfaces.conf\" | xargs -r sudo -n sed -i \"s/^interface=.*/# removed by sync/g\" || echo \"Warning: Could not clean interfaces in config files\"
        
        # 3. Handle setup_firewall.sh
        if [ -f /home/dns/setup_firewall.sh ]; then
             sudo -n sed -i \"s/ens18/$REMOTE_IFACE/g\" /home/dns/setup_firewall.sh || echo \"Warning: Could not update firewall script\"
        fi
    fi

    # Restart Services
    echo 'Restarting services...'
    sudo -n systemctl restart unbound || echo \"Warning: Could not restart Unbound\"
    sudo -n systemctl restart dnsmasq || echo \"Warning: Could not restart dnsmasq\"
    # Restart Web GUI
    if systemctl is-active --quiet dnsmars-gui; then
        sudo -n systemctl restart dnsmars-gui || echo \"Warning: Could not restart GUI\"
    fi
"

echo "[$(date)] Sync Completed!"
