server:
    interface: 127.0.0.1
    port: 5353
    do-ip4: yes
    do-udp: yes
    do-tcp: yes
    access-control: 127.0.0.0/8 allow
    root-hints: "/usr/share/dns/root.hints"
    hide-identity: yes
    hide-version: yes
    harden-glue: yes
    harden-dnssec-stripped: yes
    use-caps-for-id: yes
    qname-minimisation: yes
    cache-min-ttl: 3600
    cache-max-ttl: 86400
    prefetch: yes
    num-threads: 8
    msg-cache-size: 100m
    rrset-cache-size: 100m
    
    # Anti DDoS / Rate Limit (Optimized for High Performance)
    # Increased limits to prevent localhost (dnsmasq) throttling
    ratelimit: 50000
    ip-ratelimit: 20000
    ratelimit-below-domain: com 5000
    ratelimit-below-domain: net 5000
    ratelimit-below-domain: org 5000

    # Optimization for CDN & High Traffic
    so-rcvbuf: 4m
    so-sndbuf: 4m
    edns-buffer-size: 1232
    serve-expired: yes
    serve-expired-ttl: 259200 # 3 days retention for expired cache
    serve-expired-client-timeout: 1800 # Give expired answer if recursion takes > 1.8s
    prefetch-key: yes
    rrset-roundrobin: yes
    neg-cache-size: 4m
    minimal-responses: yes
    
    # Slabs for parallelism (Reduces lock contention)
    msg-cache-slabs: 8
    rrset-cache-slabs: 8
    infra-cache-slabs: 8
    key-cache-slabs: 8

    # Local data for the domain
    local-zone: "mdnet.co.id." static
    local-data: "dns.mdnet.co.id. IN A 103.68.213.74"
    local-data-ptr: "103.68.213.74 dns.mdnet.co.id"
