# High Load Trackers - Null Route to save CPU
address=/pangle.io/0.0.0.0
address=/kwai-pro.com/0.0.0.0
address=/applovin.com/0.0.0.0
address=/boyuanhulian.com/0.0.0.0
address=/adjust.com/0.0.0.0
address=/appsflyersdk.com/0.0.0.0
address=/criteo.com/0.0.0.0
address=/unity3d.com/0.0.0.0
address=/ironsrc.com/0.0.0.0
