# Google SafeSearch (forcesafesearch.google.com)
address=/www.google.com/216.239.38.120
address=/www.google.co.id/216.239.38.120
address=/google.com/216.239.38.120
address=/google.co.id/216.239.38.120

# Bing SafeSearch (strict.bing.com)
address=/www.bing.com/204.79.197.220
address=/bing.com/204.79.197.220

# DuckDuckGo SafeSearch (safe.duckduckgo.com)
address=/duckduckgo.com/20.43.161.151
address=/www.duckduckgo.com/20.43.161.151

# Yandex Family Search (family.yandex.com)
address=/yandex.com/213.180.204.242
address=/www.yandex.com/213.180.204.242
address=/yandex.ru/213.180.204.242
address=/www.yandex.ru/213.180.204.242
