server=/dns.mdnet.co.id/8.8.8.8
server=/radius.mdnet.co.id/8.8.8.8
server=/reddit.com/8.8.8.8
server=/103.68.213.6/8.8.8.8
server=/103.68.213.7/8.8.8.8
server=/luciferdonghua.org/8.8.8.8
server=/googleads.g.doubleclick.net/8.8.8.8
